#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<math.h>
#include<string.h>
#include<errno.h>
#include<string.h>
#include<stdarg.h>
#include<sys/stat.h>
#include<time.h>
#include<sys/timeb.h>
